# Generated by Django 4.2.2 on 2023-06-27 01:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0012_remove_schedule_total_budget_schedule_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_groups', to='schedule.schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_users', to='schedule.schedule')),
            ],
        ),
    ]
