# Generated by Django 4.2.2 on 2023-06-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='プロフィール画像'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='誕生日'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID'),
        ),
    ]
