# Generated by Django 4.2.2 on 2023-06-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_bio_customuser_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='ID'),
        ),
    ]
