# Generated by Django 4.2.2 on 2023-06-23 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_login_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='login_id',
        ),
    ]
