# Generated by Django 4.2.2 on 2023-06-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='article_images/', verbose_name='画像'),
        ),
    ]
