# Generated by Django 4.2.2 on 2023-06-22 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('duration_begin', models.DateField(blank=True, null=True, verbose_name='期間開始日')),
                ('duration_end', models.DateField(blank=True, null=True, verbose_name='期間終了日')),
                ('total_budget', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000000000)], verbose_name='予算合計')),
                ('place', models.CharField(max_length=255, verbose_name='場所')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='日時')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='schedule_images/', verbose_name='画像')),
                ('budget', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000000000)], verbose_name='予算')),
            ],
        ),
    ]
