# Generated by Django 4.2.2 on 2023-06-23 01:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedule_budget_alter_schedule_total_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='budget',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000000000)], verbose_name='予算'),
        ),
    ]
