# Generated by Django 4.2.2 on 2023-06-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_plan_remove_schedule_budget_remove_schedule_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plan_images/', verbose_name='画像'),
        ),
    ]
