# Generated by Django 4.2.2 on 2023-06-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_plan_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
