# Generated by Django 4.2.2 on 2023-06-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_plan_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['datetime']},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['duration_begin']},
        ),
    ]
