# Generated by Django 4.2.2 on 2023-06-26 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0011_alter_plan_options_alter_schedule_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='total_budget',
        ),
        migrations.AddField(
            model_name='schedule',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
