# Generated by Django 4.2.2 on 2023-06-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_categories'),
        ('schedule', '0013_schedule_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='categories',
            field=models.ManyToManyField(blank=True, to='article.category'),
        ),
    ]
